services:
  ui:
    build: ./ui
    container_name: projetsession-ui
    restart: always
    depends_on:
     - api
    ports:
     - 8080:8080 

  api:
    build: .
    container_name: projetsession-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: pass
      DB_PORT: 5432
      DB_NAME: api8inf349
      REDIS_URL: redis://cache

  db:
    image: postgres:12
    container_name: projetsession-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: api8inf349
    healthcheck:
      test: pg_isready -h localhost -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 1s
      timeout: 5s
      retries: 10

  cache:
    image: redis:5
    container_name: projetsession-cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 5s
      retries: 10
    

volumes:
  pgdata:
  redis_data:
