services:
  api8inf349:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: pass
      DB_PORT: 5432
      DB_NAME: api8inf349
  db:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: api8inf349
    healthcheck:
      test: pg_isready -h localhost -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
