name: Run tests
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Start cache and database
        uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          services: |
            db
            cache
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencues
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          flask worker & python -m pytest
        env:
          FLASK_APP: api8inf349
          DB_HOST: localhost
          DB_USER: user
          DB_PASSWORD: pass
          DB_PORT: 5432
          DB_NAME: api8inf349
          REDIS_URL: redis://localhost
